### ISSUE TITLE
Article does not display

### ISSUE THREAD

**Issue by mlevin2** [Ulbora/ulboracms#4]
Hey folks,

Is this project even active?

I installed and ran the out-of-the-box demo. I created a new article and it saved correctly, but when I view the demo site, it is not displayed anywhere. I'm running the docker process in interactive mode and I can see in the output that the article is being returned from the database, but it is nowhere to be found on the page.

This project sounds like it has all the features I'm looking for, but it seems like a no-go if even the most basic example doesn't work. It was also not very obvious how to get the demo site up and running.

`requested page: /about
page: about
page: about
found cashed page{"articleLocations":{"FrontPage":[{"_id":"57926ff6aabf211000f1bdff","alias":"testing2","title":"testing","section":{"_id":"57926fb7aabf211000f1bdf2","name":"About","language":"57926fb7aabf211000f1bdeb","__v":0},"category":{"_id":"57926fb7aabf211000f1bdf6","name":"News","language":"57926fb7aabf211000f1bdeb","__v":0},"accessLevel":"57926fb7aabf211000f1bde9","language":"57926fb7aabf211000f1bdeb","user":{"_id":"57926fb7aabf211000f1bde8","firstName":"super","lastName":"administrator","emailAddress":"admin@ulboracms.com"},"__v":0,"commentsEndDate":null,"commentsStartDate":null,"metaAuthorName":"test","metaDesc":"test","metaKeyWords":"test","metaRobotKeyWords":"test","modifiedDate":"2016-07-22T19:16:45.543Z","menuIndex":0,"commentsRequireLogin":true,"allowComments":false,"fullPage":true,"showTitle":true,"showSectionName":true,"showModifyDate":true,"showIntroText":false,"showCreateDate":true,"showCategoryName":true,"showAuthor":true,"published":true,"hits":0,"createdDate":"2016-07-22T00:00:00.000Z","articleText":{"_id":"57926ff6aabf211000f1be00","text":"<p>test!</p>","version":1,"article":"57926ff6aabf211000f1bdff","__v":0,"active":true,"processed":true},"frontPage":true,"articleLocationList":["57926fb7aabf211000f1bdfa"],"tag":{"_id":"579270b4aabf211000f1be05","keyWords":"test","article":"57926ff6aabf211000f1bdff","__v":0}}],"TopMenu":[],"Left":[{"_id":"57926ff6aabf211000f1bdff","alias":"testing2","title":"testing","section":{"_id":"57926fb7aabf211000f1bdf2","name":"About","language":"57926fb7aabf211000f1bdeb","__v":0},"category":{"_id":"57926fb7aabf211000f1bdf6","name":"News","language":"57926fb7aabf211000f1bdeb","__v":0},"accessLevel":"57926fb7aabf211000f1bde9","language":"57926fb7aabf211000f1bdeb","user":{"_id":"57926fb7aabf211000f1bde8","firstName":"super","lastName":"administrator","emailAddress":"admin@ulboracms.com"},"__v":0,"commentsEndDate":null,"commentsStartDate":null,"metaAuthorName":"test","metaDesc":"test","metaKeyWords":"test","metaRobotKeyWords":"test","modifiedDate":"2016-07-22T19:16:45.543Z","menuIndex":0,"commentsRequireLogin":true,"allowComments":false,"fullPage":true,"showTitle":true,"showSectionName":true,"showModifyDate":true,"showIntroText":false,"showCreateDate":true,"showCategoryName":true,"showAuthor":true,"published":true,"hits":0,"createdDate":"2016-07-22T00:00:00.000Z","position":["Left"],"articleText":{"_id":"57926ff6aabf211000f1be00","text":"<p>test!</p>","version":1,"article":"57926ff6aabf211000f1bdff","__v":0,"active":true,"processed":true},"frontPage":false,"articleLocationList":["57926fb7aabf211000f1bdfa"],"tag":{"_id":"579270b4aabf211000f1be05","keyWords":"test","article":"57926ff6aabf211000f1bdff","__v":0}}],"Right":[],"Center":[]},"productLocations":{"TopMenu":[],"Left":[],"Right":[],"Center":[]},"links":[],"dates":[{"dateLabel":"July 2016","month":6,"year":2016}]}
GET /about 304 10.257 ms - -`

**Comment by KenWilliamson** [comment]
Which Ulboracms version, which template, and is it on docker or on a stand alone node server?
It looks there is a mismatch between the article section/category and the template you are using.
If you add an article with a particular section/category, then then you need to make sure the template has that particular section/category on the page where you want to view that.

If you are using Docker, did you restore the mongo database as described here https://hub.docker.com/r/ulboralabs/ulboracms-mongo/

**Comment by KenWilliamson** [comment]
This was a user error: closing.
